version: '3.8'
services:
  sample-api:
    container_name: sample-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: air -c .air.toml
    ports:
      - "3000:3000"
    environment:
      ENV: docker
      PORT: 3000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_HOST: sample-mysql
      MYSQL_PORT: 3306
    depends_on:
      - sample-mysql
    volumes:
      - ./:/go/src/app
    working_dir: /go/src/app
    networks:
      - sample

  sample-mysql:
    container_name: sample-mysql
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - sample
    # volumes:
    #   - ./mysql/init:/docker-entrypoint-initdb.d
    #   - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

networks:
  sample: