version: '3.8'
services:

  sample-api:
    container_name: sample-api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: air -c .air.toml
    ports:
      - "3000:3000"
    environment:
      ENV: docker
      PORT: 3000
    # depends_on:
    #   - sample-mysql
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    networks:
      - sample

networks:
  sample:
    external: true
